//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/BlophyNovaEdit.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace BlophyNovaInput
{
    public partial class @BlophyNovaInput: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @BlophyNovaInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""BlophyNovaEdit"",
    ""maps"": [
        {
            ""name"": ""UI"",
            ""id"": ""ecef422e-b64f-4e18-8925-e652a6527c05"",
            ""actions"": [
                {
                    ""name"": ""AddTap"",
                    ""type"": ""Button"",
                    ""id"": ""18a825aa-5c31-4344-9830-910fa89ef19b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddHold"",
                    ""type"": ""Button"",
                    ""id"": ""1aa1413e-e318-4e21-b883-8a249e548d67"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddDrag"",
                    ""type"": ""Button"",
                    ""id"": ""fcd852a0-fa50-4f32-95f7-55719913a1f2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddFlick"",
                    ""type"": ""Button"",
                    ""id"": ""7ae62d85-7285-4cb7-a1d8-a4c0fbcfaccb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddPoint"",
                    ""type"": ""Button"",
                    ""id"": ""d56b8b81-0a9f-4138-8c68-f63bb92e285c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddFullFlick"",
                    ""type"": ""Button"",
                    ""id"": ""b6a3b011-3ed5-448f-a353-a7cfa725eed4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddEvent"",
                    ""type"": ""Button"",
                    ""id"": ""5f3bf843-35e8-4bc7-a6ba-3b50b020ee2e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Undo"",
                    ""type"": ""Button"",
                    ""id"": ""88a1a783-9dfc-4c45-96a4-8e72606badfc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Redo"",
                    ""type"": ""Button"",
                    ""id"": ""c558b8eb-d92c-4bbf-8b22-82bb6f4352fe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Copy"",
                    ""type"": ""Button"",
                    ""id"": ""09db9b8d-724c-4226-ac66-b2761965749d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Paste"",
                    ""type"": ""Button"",
                    ""id"": ""588e6070-a285-49b5-9fd7-0141390350d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Save"",
                    ""type"": ""Button"",
                    ""id"": ""a23ee171-550f-4996-b3ed-d867529eb596"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Delete"",
                    ""type"": ""Button"",
                    ""id"": ""55f9d8e0-be72-4170-b8a7-8c0cb8394959"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchLine1"",
                    ""type"": ""Button"",
                    ""id"": ""f661cd96-1e34-440b-a00d-6d2d1c088f38"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchLine2"",
                    ""type"": ""Button"",
                    ""id"": ""82334463-90fc-4d0f-b041-98fa93c08306"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchLine3"",
                    ""type"": ""Button"",
                    ""id"": ""bc51a342-0c6d-406d-8dc6-38d7b886b3c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchLine4"",
                    ""type"": ""Button"",
                    ""id"": ""835fbc79-1754-498a-9a02-36b47a58c407"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchLine5"",
                    ""type"": ""Button"",
                    ""id"": ""f76e8f51-be40-435b-90b7-2e238d240c8c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HoldPlayPlayer"",
                    ""type"": ""Button"",
                    ""id"": ""00794f54-fcd2-4b64-837b-271f7bbf58d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayPlayer"",
                    ""type"": ""Button"",
                    ""id"": ""fd5c2ac4-5bef-422d-9872-b07c81a623a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayEdit"",
                    ""type"": ""Button"",
                    ""id"": ""a1c73658-b090-4625-aeb4-5962e0a0a08e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HoldPlayEdit"",
                    ""type"": ""Button"",
                    ""id"": ""a265c0e7-5737-475b-b9ee-51dec0faf35f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseResume"",
                    ""type"": ""Button"",
                    ""id"": ""2ed91bc3-a036-469c-a503-af2da462441c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""02357d26-118a-42bb-9e15-352651bb6c66"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""AddTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be37481a-906a-44c0-abaf-e1c5e350f633"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""AddHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c39fec3-f5a9-440b-ba7f-f7d436ad3498"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""AddDrag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b1a16ff-d0ee-42e4-a7a5-8a916c5f00fd"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""AddFlick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""238eaf6b-cf40-4b47-9ad0-4c0097c82588"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""AddPoint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b7145ae-e13b-41e5-8372-9ba7b0514409"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""AddFullFlick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39852de6-2b3e-4805-9f16-7a5bc0531074"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""AddEvent"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""d3d3be30-b2c4-46af-810a-781cb5bb281d"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Undo"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""b3f25878-0df9-4ef1-b997-5fe6f31bbeb6"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Undo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""4dcb7b3e-7300-49a0-8143-f1b87f9d91f9"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Undo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""d124380c-8c2e-4089-bf7f-3f831d21080e"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Redo"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""94224e16-d3d1-45c1-9f58-402a296c0e44"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Redo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""9c1042a7-a309-492f-b97d-c046baf10033"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Redo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""a1fa6246-d4d3-4ac2-ab75-e43deb17840c"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Copy"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""32cb6a54-c303-4a3e-a00d-13692eb81afe"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Copy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""5ac8b4d6-d05b-44ce-b0ff-19ebbaa1e9fe"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Copy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""04fc892c-9f2b-4943-b6e1-e24c4e8320e2"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Save"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""4d589077-8c0b-4153-bbd7-24ee18839bd8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Save"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""789fb428-cb4c-4225-965d-62afcf1baef6"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Save"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""62cd45ea-9bff-477b-8746-b6e4ca68a98b"",
                    ""path"": ""<Keyboard>/delete"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""19326b23-beed-4800-9b29-e3c7ad39c685"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""ae428f09-f79b-4fe5-b988-744882eb64cd"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""4654c84f-2ab6-4615-a6b8-1773325c457d"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9a9cced6-f747-478e-91e5-115ac35f92f6"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SwitchLine1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5dd66da3-f948-41c0-b0ce-59a4acaebcd9"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SwitchLine2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""220a4380-faa9-4a4e-b908-575ec50347d4"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SwitchLine3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a802e213-f75a-4ef6-8783-c82017fd231b"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SwitchLine4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78b9cfea-174c-46ff-807c-a32c8e30aa58"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SwitchLine5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""adff2461-2954-4456-a3b3-b2c7eab16b20"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""HoldPlayPlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""331a9c63-1051-4e25-bb72-40dadf95f30d"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""PlayPlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86630b80-64a5-4f5c-9a83-3de9cd99d08a"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""PlayEdit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb308e5f-da6c-4f81-8a01-7827a8151842"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""HoldPlayEdit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""89a93f4d-a75e-4fb7-9bdb-44f10d77d408"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Paste"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""3817fae5-8e5e-482a-8405-a0b7bdde1a6f"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Paste"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""5bff7ae3-9479-4d2b-a8a7-86dd173d4ebc"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Paste"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b3dff185-c583-40d9-954e-a41003ca0394"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""PauseResume"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // UI
            m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
            m_UI_AddTap = m_UI.FindAction("AddTap", throwIfNotFound: true);
            m_UI_AddHold = m_UI.FindAction("AddHold", throwIfNotFound: true);
            m_UI_AddDrag = m_UI.FindAction("AddDrag", throwIfNotFound: true);
            m_UI_AddFlick = m_UI.FindAction("AddFlick", throwIfNotFound: true);
            m_UI_AddPoint = m_UI.FindAction("AddPoint", throwIfNotFound: true);
            m_UI_AddFullFlick = m_UI.FindAction("AddFullFlick", throwIfNotFound: true);
            m_UI_AddEvent = m_UI.FindAction("AddEvent", throwIfNotFound: true);
            m_UI_Undo = m_UI.FindAction("Undo", throwIfNotFound: true);
            m_UI_Redo = m_UI.FindAction("Redo", throwIfNotFound: true);
            m_UI_Copy = m_UI.FindAction("Copy", throwIfNotFound: true);
            m_UI_Paste = m_UI.FindAction("Paste", throwIfNotFound: true);
            m_UI_Save = m_UI.FindAction("Save", throwIfNotFound: true);
            m_UI_Delete = m_UI.FindAction("Delete", throwIfNotFound: true);
            m_UI_SwitchLine1 = m_UI.FindAction("SwitchLine1", throwIfNotFound: true);
            m_UI_SwitchLine2 = m_UI.FindAction("SwitchLine2", throwIfNotFound: true);
            m_UI_SwitchLine3 = m_UI.FindAction("SwitchLine3", throwIfNotFound: true);
            m_UI_SwitchLine4 = m_UI.FindAction("SwitchLine4", throwIfNotFound: true);
            m_UI_SwitchLine5 = m_UI.FindAction("SwitchLine5", throwIfNotFound: true);
            m_UI_HoldPlayPlayer = m_UI.FindAction("HoldPlayPlayer", throwIfNotFound: true);
            m_UI_PlayPlayer = m_UI.FindAction("PlayPlayer", throwIfNotFound: true);
            m_UI_PlayEdit = m_UI.FindAction("PlayEdit", throwIfNotFound: true);
            m_UI_HoldPlayEdit = m_UI.FindAction("HoldPlayEdit", throwIfNotFound: true);
            m_UI_PauseResume = m_UI.FindAction("PauseResume", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // UI
        private readonly InputActionMap m_UI;
        private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
        private readonly InputAction m_UI_AddTap;
        private readonly InputAction m_UI_AddHold;
        private readonly InputAction m_UI_AddDrag;
        private readonly InputAction m_UI_AddFlick;
        private readonly InputAction m_UI_AddPoint;
        private readonly InputAction m_UI_AddFullFlick;
        private readonly InputAction m_UI_AddEvent;
        private readonly InputAction m_UI_Undo;
        private readonly InputAction m_UI_Redo;
        private readonly InputAction m_UI_Copy;
        private readonly InputAction m_UI_Paste;
        private readonly InputAction m_UI_Save;
        private readonly InputAction m_UI_Delete;
        private readonly InputAction m_UI_SwitchLine1;
        private readonly InputAction m_UI_SwitchLine2;
        private readonly InputAction m_UI_SwitchLine3;
        private readonly InputAction m_UI_SwitchLine4;
        private readonly InputAction m_UI_SwitchLine5;
        private readonly InputAction m_UI_HoldPlayPlayer;
        private readonly InputAction m_UI_PlayPlayer;
        private readonly InputAction m_UI_PlayEdit;
        private readonly InputAction m_UI_HoldPlayEdit;
        private readonly InputAction m_UI_PauseResume;
        public struct UIActions
        {
            private @BlophyNovaInput m_Wrapper;
            public UIActions(@BlophyNovaInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @AddTap => m_Wrapper.m_UI_AddTap;
            public InputAction @AddHold => m_Wrapper.m_UI_AddHold;
            public InputAction @AddDrag => m_Wrapper.m_UI_AddDrag;
            public InputAction @AddFlick => m_Wrapper.m_UI_AddFlick;
            public InputAction @AddPoint => m_Wrapper.m_UI_AddPoint;
            public InputAction @AddFullFlick => m_Wrapper.m_UI_AddFullFlick;
            public InputAction @AddEvent => m_Wrapper.m_UI_AddEvent;
            public InputAction @Undo => m_Wrapper.m_UI_Undo;
            public InputAction @Redo => m_Wrapper.m_UI_Redo;
            public InputAction @Copy => m_Wrapper.m_UI_Copy;
            public InputAction @Paste => m_Wrapper.m_UI_Paste;
            public InputAction @Save => m_Wrapper.m_UI_Save;
            public InputAction @Delete => m_Wrapper.m_UI_Delete;
            public InputAction @SwitchLine1 => m_Wrapper.m_UI_SwitchLine1;
            public InputAction @SwitchLine2 => m_Wrapper.m_UI_SwitchLine2;
            public InputAction @SwitchLine3 => m_Wrapper.m_UI_SwitchLine3;
            public InputAction @SwitchLine4 => m_Wrapper.m_UI_SwitchLine4;
            public InputAction @SwitchLine5 => m_Wrapper.m_UI_SwitchLine5;
            public InputAction @HoldPlayPlayer => m_Wrapper.m_UI_HoldPlayPlayer;
            public InputAction @PlayPlayer => m_Wrapper.m_UI_PlayPlayer;
            public InputAction @PlayEdit => m_Wrapper.m_UI_PlayEdit;
            public InputAction @HoldPlayEdit => m_Wrapper.m_UI_HoldPlayEdit;
            public InputAction @PauseResume => m_Wrapper.m_UI_PauseResume;
            public InputActionMap Get() { return m_Wrapper.m_UI; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
            public void AddCallbacks(IUIActions instance)
            {
                if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
                @AddTap.started += instance.OnAddTap;
                @AddTap.performed += instance.OnAddTap;
                @AddTap.canceled += instance.OnAddTap;
                @AddHold.started += instance.OnAddHold;
                @AddHold.performed += instance.OnAddHold;
                @AddHold.canceled += instance.OnAddHold;
                @AddDrag.started += instance.OnAddDrag;
                @AddDrag.performed += instance.OnAddDrag;
                @AddDrag.canceled += instance.OnAddDrag;
                @AddFlick.started += instance.OnAddFlick;
                @AddFlick.performed += instance.OnAddFlick;
                @AddFlick.canceled += instance.OnAddFlick;
                @AddPoint.started += instance.OnAddPoint;
                @AddPoint.performed += instance.OnAddPoint;
                @AddPoint.canceled += instance.OnAddPoint;
                @AddFullFlick.started += instance.OnAddFullFlick;
                @AddFullFlick.performed += instance.OnAddFullFlick;
                @AddFullFlick.canceled += instance.OnAddFullFlick;
                @AddEvent.started += instance.OnAddEvent;
                @AddEvent.performed += instance.OnAddEvent;
                @AddEvent.canceled += instance.OnAddEvent;
                @Undo.started += instance.OnUndo;
                @Undo.performed += instance.OnUndo;
                @Undo.canceled += instance.OnUndo;
                @Redo.started += instance.OnRedo;
                @Redo.performed += instance.OnRedo;
                @Redo.canceled += instance.OnRedo;
                @Copy.started += instance.OnCopy;
                @Copy.performed += instance.OnCopy;
                @Copy.canceled += instance.OnCopy;
                @Paste.started += instance.OnPaste;
                @Paste.performed += instance.OnPaste;
                @Paste.canceled += instance.OnPaste;
                @Save.started += instance.OnSave;
                @Save.performed += instance.OnSave;
                @Save.canceled += instance.OnSave;
                @Delete.started += instance.OnDelete;
                @Delete.performed += instance.OnDelete;
                @Delete.canceled += instance.OnDelete;
                @SwitchLine1.started += instance.OnSwitchLine1;
                @SwitchLine1.performed += instance.OnSwitchLine1;
                @SwitchLine1.canceled += instance.OnSwitchLine1;
                @SwitchLine2.started += instance.OnSwitchLine2;
                @SwitchLine2.performed += instance.OnSwitchLine2;
                @SwitchLine2.canceled += instance.OnSwitchLine2;
                @SwitchLine3.started += instance.OnSwitchLine3;
                @SwitchLine3.performed += instance.OnSwitchLine3;
                @SwitchLine3.canceled += instance.OnSwitchLine3;
                @SwitchLine4.started += instance.OnSwitchLine4;
                @SwitchLine4.performed += instance.OnSwitchLine4;
                @SwitchLine4.canceled += instance.OnSwitchLine4;
                @SwitchLine5.started += instance.OnSwitchLine5;
                @SwitchLine5.performed += instance.OnSwitchLine5;
                @SwitchLine5.canceled += instance.OnSwitchLine5;
                @HoldPlayPlayer.started += instance.OnHoldPlayPlayer;
                @HoldPlayPlayer.performed += instance.OnHoldPlayPlayer;
                @HoldPlayPlayer.canceled += instance.OnHoldPlayPlayer;
                @PlayPlayer.started += instance.OnPlayPlayer;
                @PlayPlayer.performed += instance.OnPlayPlayer;
                @PlayPlayer.canceled += instance.OnPlayPlayer;
                @PlayEdit.started += instance.OnPlayEdit;
                @PlayEdit.performed += instance.OnPlayEdit;
                @PlayEdit.canceled += instance.OnPlayEdit;
                @HoldPlayEdit.started += instance.OnHoldPlayEdit;
                @HoldPlayEdit.performed += instance.OnHoldPlayEdit;
                @HoldPlayEdit.canceled += instance.OnHoldPlayEdit;
                @PauseResume.started += instance.OnPauseResume;
                @PauseResume.performed += instance.OnPauseResume;
                @PauseResume.canceled += instance.OnPauseResume;
            }

            private void UnregisterCallbacks(IUIActions instance)
            {
                @AddTap.started -= instance.OnAddTap;
                @AddTap.performed -= instance.OnAddTap;
                @AddTap.canceled -= instance.OnAddTap;
                @AddHold.started -= instance.OnAddHold;
                @AddHold.performed -= instance.OnAddHold;
                @AddHold.canceled -= instance.OnAddHold;
                @AddDrag.started -= instance.OnAddDrag;
                @AddDrag.performed -= instance.OnAddDrag;
                @AddDrag.canceled -= instance.OnAddDrag;
                @AddFlick.started -= instance.OnAddFlick;
                @AddFlick.performed -= instance.OnAddFlick;
                @AddFlick.canceled -= instance.OnAddFlick;
                @AddPoint.started -= instance.OnAddPoint;
                @AddPoint.performed -= instance.OnAddPoint;
                @AddPoint.canceled -= instance.OnAddPoint;
                @AddFullFlick.started -= instance.OnAddFullFlick;
                @AddFullFlick.performed -= instance.OnAddFullFlick;
                @AddFullFlick.canceled -= instance.OnAddFullFlick;
                @AddEvent.started -= instance.OnAddEvent;
                @AddEvent.performed -= instance.OnAddEvent;
                @AddEvent.canceled -= instance.OnAddEvent;
                @Undo.started -= instance.OnUndo;
                @Undo.performed -= instance.OnUndo;
                @Undo.canceled -= instance.OnUndo;
                @Redo.started -= instance.OnRedo;
                @Redo.performed -= instance.OnRedo;
                @Redo.canceled -= instance.OnRedo;
                @Copy.started -= instance.OnCopy;
                @Copy.performed -= instance.OnCopy;
                @Copy.canceled -= instance.OnCopy;
                @Paste.started -= instance.OnPaste;
                @Paste.performed -= instance.OnPaste;
                @Paste.canceled -= instance.OnPaste;
                @Save.started -= instance.OnSave;
                @Save.performed -= instance.OnSave;
                @Save.canceled -= instance.OnSave;
                @Delete.started -= instance.OnDelete;
                @Delete.performed -= instance.OnDelete;
                @Delete.canceled -= instance.OnDelete;
                @SwitchLine1.started -= instance.OnSwitchLine1;
                @SwitchLine1.performed -= instance.OnSwitchLine1;
                @SwitchLine1.canceled -= instance.OnSwitchLine1;
                @SwitchLine2.started -= instance.OnSwitchLine2;
                @SwitchLine2.performed -= instance.OnSwitchLine2;
                @SwitchLine2.canceled -= instance.OnSwitchLine2;
                @SwitchLine3.started -= instance.OnSwitchLine3;
                @SwitchLine3.performed -= instance.OnSwitchLine3;
                @SwitchLine3.canceled -= instance.OnSwitchLine3;
                @SwitchLine4.started -= instance.OnSwitchLine4;
                @SwitchLine4.performed -= instance.OnSwitchLine4;
                @SwitchLine4.canceled -= instance.OnSwitchLine4;
                @SwitchLine5.started -= instance.OnSwitchLine5;
                @SwitchLine5.performed -= instance.OnSwitchLine5;
                @SwitchLine5.canceled -= instance.OnSwitchLine5;
                @HoldPlayPlayer.started -= instance.OnHoldPlayPlayer;
                @HoldPlayPlayer.performed -= instance.OnHoldPlayPlayer;
                @HoldPlayPlayer.canceled -= instance.OnHoldPlayPlayer;
                @PlayPlayer.started -= instance.OnPlayPlayer;
                @PlayPlayer.performed -= instance.OnPlayPlayer;
                @PlayPlayer.canceled -= instance.OnPlayPlayer;
                @PlayEdit.started -= instance.OnPlayEdit;
                @PlayEdit.performed -= instance.OnPlayEdit;
                @PlayEdit.canceled -= instance.OnPlayEdit;
                @HoldPlayEdit.started -= instance.OnHoldPlayEdit;
                @HoldPlayEdit.performed -= instance.OnHoldPlayEdit;
                @HoldPlayEdit.canceled -= instance.OnHoldPlayEdit;
                @PauseResume.started -= instance.OnPauseResume;
                @PauseResume.performed -= instance.OnPauseResume;
                @PauseResume.canceled -= instance.OnPauseResume;
            }

            public void RemoveCallbacks(IUIActions instance)
            {
                if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IUIActions instance)
            {
                foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public UIActions @UI => new UIActions(this);
        private int m_KeyboardMouseSchemeIndex = -1;
        public InputControlScheme KeyboardMouseScheme
        {
            get
            {
                if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
                return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
            }
        }
        private int m_GamepadSchemeIndex = -1;
        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }
        private int m_TouchSchemeIndex = -1;
        public InputControlScheme TouchScheme
        {
            get
            {
                if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
                return asset.controlSchemes[m_TouchSchemeIndex];
            }
        }
        private int m_JoystickSchemeIndex = -1;
        public InputControlScheme JoystickScheme
        {
            get
            {
                if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
                return asset.controlSchemes[m_JoystickSchemeIndex];
            }
        }
        private int m_XRSchemeIndex = -1;
        public InputControlScheme XRScheme
        {
            get
            {
                if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
                return asset.controlSchemes[m_XRSchemeIndex];
            }
        }
        public interface IUIActions
        {
            void OnAddTap(InputAction.CallbackContext context);
            void OnAddHold(InputAction.CallbackContext context);
            void OnAddDrag(InputAction.CallbackContext context);
            void OnAddFlick(InputAction.CallbackContext context);
            void OnAddPoint(InputAction.CallbackContext context);
            void OnAddFullFlick(InputAction.CallbackContext context);
            void OnAddEvent(InputAction.CallbackContext context);
            void OnUndo(InputAction.CallbackContext context);
            void OnRedo(InputAction.CallbackContext context);
            void OnCopy(InputAction.CallbackContext context);
            void OnPaste(InputAction.CallbackContext context);
            void OnSave(InputAction.CallbackContext context);
            void OnDelete(InputAction.CallbackContext context);
            void OnSwitchLine1(InputAction.CallbackContext context);
            void OnSwitchLine2(InputAction.CallbackContext context);
            void OnSwitchLine3(InputAction.CallbackContext context);
            void OnSwitchLine4(InputAction.CallbackContext context);
            void OnSwitchLine5(InputAction.CallbackContext context);
            void OnHoldPlayPlayer(InputAction.CallbackContext context);
            void OnPlayPlayer(InputAction.CallbackContext context);
            void OnPlayEdit(InputAction.CallbackContext context);
            void OnHoldPlayEdit(InputAction.CallbackContext context);
            void OnPauseResume(InputAction.CallbackContext context);
        }
    }
}
